---
title: "Lab 3"
author: "Sylvia Du"
date: "2/10/20"
output: html_document
---

```{r, eval = TRUE, echo = TRUE, message = FALSE}
# import libraries that are needed in this lab
library(tidyverse)
library(stringr)
```


## Part 1. t-test


```{r, eval = TRUE, echo = TRUE}
# function: my_t.test, apply t test to input data
# input: numeric data vector x, string alternative to specify aternative 
#        hypothesis, null hypothesis numeric value mu
# output: a list object of result result
my_t.test <- function(x, alternative, mu) {
    # check if x is numeric, if not stop and show error information
    if (!is.numeric(x)) {
        stop("x should be numeric")
    } 
    # check if alternative is one of "two.sided", "less", "greater",
    # if not stop and show error information
      else if (alternative != "two.sided" & alternative != "less"
               & alternative != "greater") {
        stop("alternative should be either 'two.sided', 'less', or 'greater'")
    } # check if mu is numeric, if not stop and show error information
      else if (!is.numeric(mu)) {
        stop("mu should be numeric")
    }
    se <- sd(x) / sqrt(length(x))
    test_stat <- (mean(x) - mu) / se
    df <- length(x) - 1
    # use methods for different type of alternative hypothesis respectively
    if (alternative == "two.sided") {
        p_val <- 2 * min(pt(test_stat, df, lower.tail = TRUE), 
                         pt(test_stat, df, lower.tail = FALSE))
    } else if (alternative == "less") {
        p_val <- pt(test_stat, df, lower.tail = TRUE)
    } else {  # alternative == "greater"
        p_val <- pt(test_stat, df, lower.tail = FALSE)
    }
    result <- list("t score" = test_stat, "degree of freedom" = df, 
                   "type of alternative hypothesis" = alternative, 
                   "p value" = p_val)
    return(result)
}
```

```{r, eval = TRUE, echo = TRUE}
# test my_t.test by comparing the result of built-in function t.test and 
# my_t.test using same data
set.seed(1)
test <- rnorm(10, mean = 0, sd = 1)
t.test(test, mu = 0)
my_t.test(test, "two.sided", 0)
```


## Part 2. Linear Model

```{r, eval = TRUE, echo = TRUE}
# function: my_lm, apply linear model to input data
# input: a formula class object formula, a dataframe data
# output: a table object of result my_t
my_lm <- function(formula, data) {
    x <- model.matrix(formula, data)
    f <- model.frame(formula, data)
    y <- model.response(f)
    coeff <- solve(t(x) %*% x) %*% t(x) %*% y
    df <- dim(x)[1] - length(coeff)
    sigma_sqr <- sum((y - x %*% coeff)^2 / df)
    se <- sqrt(diag(sigma_sqr * solve(t(x) %*% x)))
    t_val <- t(coeff) / se
    pr_t <- 2 * pt(abs(t_val), df, lower.tail = FALSE)
    
    # binding the data together and convert the data matrix into a table
    my_m <- cbind(coeff, se, t(t_val), t(pr_t))
    colnames(my_m) <- c("Estimate", "Std. Error", "t value", "Pr(>|t|)")
    my_t <- as.table(my_m)
    return(my_t)
}
```

```{r, eval = TRUE, echo = TRUE}
# test my_lm by comparing the result of built-in function lm and my_lm using
# same data
my_lm(mpg ~ hp + wt, mtcars)
summary(lm(mpg ~ hp + wt, mtcars))
```








